services:
  owl:
    build: .
    container_name: owl_backend
    env_file:
      - path: .env
        required: false
      - path: .env.default
        required: true
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./owl_core:/app/owl_core
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - path: .env
        required: false
      - path: .env.default
        required: true
    ports:
      - "5432:5433"
    volumes:
      - owl-data:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules         # кеш для npm ci
    command: sh -c "npm ci && npm run dev -- --host"
    environment:
      - VITE_API_URL=http://localhost:8000   # внутри сети compose
    ports:
      - "5173:5173"
    depends_on:
      - owl

volumes:
  owl-data:
    external: false