version: "3.9"

services:
  api:
    build: .
    container_name: owl_backend
    env_file:
      - .env                # optional: keep secrets out of git
    environment:
      # fallback values if .env is missing
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/owl_db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app           # монтируем корень проекта
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: owl_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: