version: "3.9"

services:
  owl:
    build: .
    container_name: owl_backend
    env_file:
      - path: .env-default
        required: true
      - path: .env
        required: false
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - path: .env-default
        required: true
      - path: .env
        required: false
    ports:
      - "5432:5432"
    volumes:
      - owl-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  owl-data:
    external: false