"""Added hidden field for reviews

Revision ID: 027b2833eaac
Revises: 8d8ef2b62493
Create Date: 2025-06-30 15:06:25.988077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "027b2833eaac"
down_revision: Union[str, Sequence[str], None] = "8d8ef2b62493"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews",
        sa.Column("hidden", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "hidden")
    # ### end Alembic commands ###
