"""Drop slugs

Revision ID: 8d8ef2b62493
Revises: 31195ccab2a2
Create Date: 2025-06-25 13:04:32.106774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d8ef2b62493'
down_revision: Union[str, Sequence[str], None] = '31195ccab2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_column('tags', 'slug')
    op.drop_index(op.f('ix_titles_slug'), table_name='titles')
    op.drop_column('titles', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_titles_slug'), 'titles', ['slug'], unique=True)
    op.add_column('tags', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    # ### end Alembic commands ###
