"""Remove review descriptions (had no sense)

Revision ID: 31195ccab2a2
Revises: 35800cec5194
Create Date: 2025-06-25 13:02:20.290355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31195ccab2a2"
down_revision: Union[str, Sequence[str], None] = "35800cec5194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
