"""Drop extra fkeys

Revision ID: 621725b8530d
Revises: b5708d2b55bc
Create Date: 2025-07-24 12:44:02.381350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "621725b8530d"
down_revision: Union[str, Sequence[str], None] = "b5708d2b55bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tags_author_id_fkey"), "tags", type_="foreignkey")
    op.drop_column("tags", "author_id")
    op.drop_constraint(op.f("titles_author_id_fkey"), "titles", type_="foreignkey")
    op.drop_column("titles", "author_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "titles",
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("titles_author_id_fkey"),
        "titles",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "tags",
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("tags_author_id_fkey"),
        "tags",
        "users",
        ["author_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
