"""Add titles

Revision ID: 9c0e770535eb
Revises: bde3913105ff
Create Date: 2025-06-23 14:23:19.366605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c0e770535eb"
down_revision: Union[str, Sequence[str], None] = "bde3913105ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop old reviews with no titles or users
    op.execute("DELETE FROM reviews;")
    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_titles_name"), "titles", ["name"], unique=False)
    op.create_index(op.f("ix_titles_slug"), "titles", ["slug"], unique=True)
    op.add_column("reviews", sa.Column("description", sa.String(), nullable=False))
    op.add_column("reviews", sa.Column("text", sa.Text(), nullable=False))
    op.add_column("reviews", sa.Column("author_id", sa.Integer(), nullable=False))
    op.add_column("reviews", sa.Column("title_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "reviews", "titles", ["title_id"], ["id"])
    op.create_foreign_key(None, "reviews", "users", ["author_id"], ["id"])
    op.drop_column("reviews", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_column("reviews", "title_id")
    op.drop_column("reviews", "author_id")
    op.drop_column("reviews", "text")
    op.drop_column("reviews", "description")
    op.drop_index(op.f("ix_titles_slug"), table_name="titles")
    op.drop_index(op.f("ix_titles_name"), table_name="titles")
    op.drop_table("titles")
    # ### end Alembic commands ###
